### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute 'DoubleStorageBase'

### ISSUE THREAD

**Issue by AleksanderDanilian** [saic-mdal/lama#210]
Trying to deploy model on jupiter server, get the following error. 

(inpenv) root@ff96f3cd2500:/workspace/lama# python3 bin/predict.py model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output
Traceback (most recent call last):
  File "bin/predict.py", line 14, in <module>
    from saicinpainting.evaluation.utils import move_to_device
  File "/workspace/lama/saicinpainting/evaluation/__init__.py", line 3, in <module>
    import torch
  File "/workspace/inpenv/lib/python3.8/site-packages/torch/__init__.py", line 451, in <module>
    class DoubleStorage(_C.DoubleStorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'DoubleStorageBase'

**Comment by windj007** [comment]
Hi! This issue seems to be related to your installation of pytorch. Which version are you using?

**Comment by AleksanderDanilian** [comment]
Cannot recall for sure, unfortunatelly, because was trying out different installations. Do you, by any chance, have conda configuration .yml file with all the packages and dependencies to run your script with later versions of Python? >=3.8.10 in particular? Im trying to deploy your model on a server with NVIDIA GeForce RTX 3090 Ti which does not work with Torch versions you specify in requirements (looking in the forums, it has something to do with CUDA drivers of 10.2 versions). 

Default versions of Torch and Python that work fine with this videocard are 3.8.10 for Python and 1.13.1+cu117 for torch (torch cuda version 11.7). Thanks in advance!

Base installation

**Comment by AleksanderDanilian** [comment]
[new_requirements.txt](https://github.com/saic-mdal/lama/files/10571999/new_requirements.txt)

Fixed it. With this requirements lama should work fine with 3.10.8 python and 11.7 cuda. Few imports need to be adjusted, though:
saicinpainting/training/modules/fake_fakes.py:
from kornia.constants import SamplePadding

saicinpainting/training/data/aug.py:
from albumentations.imgaug.transforms import DualIAATransform

**Comment by windj007** [comment]
> NVIDIA GeForce RTX 3090 T

Yeah, it needs cuda>=11

> Fixed it

Glad to hear you've resolved the issue!
